// Platzhalter-Wörter für das Leadership Bingo
// Diese werden später durch die echten Wörter ersetzt
export const BINGO_WORDS: string[] = [
  'Synergien nutzen',
  'Paradigmenwechsel',
  'Agile Transformation',
  'Purpose driven',
  'Stakeholder Management',
  'Change Management',
  'Best Practice',
  'Low Hanging Fruits',
  'Out of the Box',
  'Win-Win Situation',
  'Lessons Learned',
  'Deep Dive',
  'Big Picture',
  'Quick Win',
  'Game Changer',
  'Mindset Shift',
  'Value Proposition',
  'Alignment',
  'Empowerment',
  'Accountability',
  'Ownership',
  'Skalierbarkeit',
  'Resilienz',
  'Nachhaltigkeit',
  'Digitalisierung',
  'Innovation',
  'Disruption',
  'Agilität',
  'Transparenz',
  'Wertschöpfung',
  'Kernkompetenz',
  'Benchmark',
  'Roadmap',
  'KPI',
  'OKR',
];
