export const BINGO_WORDS: string[] = [
  'The solution is in the room',
  'Cool people do cool stuff',
  'Get shit done',
  'Do more with less',
  'Maximize effectiveness',
  'You are on mute',
  'Holistic approach',
  'Pain points',
  'Land the plane',
  'Best practice',
  'We always done it that way',
  'Customer obsession',
  'Help the team win',
  'When culture is weak, rules multiply. When culture is strong, trust simplifies.',
  'Maybe ask Copilot',
  'Thank you all, great input, need to run for next meeting',
  'I know, and thats why I like working with you most',
  'Great idea, I put it in the backlog',
  'Transparency',
  "Let's take a decision",
  'Conditional sign-off',
  'Half way gets you nowhere',
  'Well, with the dependencies given…',
  'In theory that sounds good',
  'Yes, and',
  'Yes, but',
  'Use synergies',
  'Culture transformation',
  'Change management',
  'Low hanging fruits',
  'Big picture',
  'Quick win',
  'Value proposition',
  'Accountability',
  'Ownership',
  'Digitilisation',
  'Scalability',
  'Resilience',
  'Sustainable growth',
  'KPI',
  'OKR',
];
