export const BINGO_WORDS: string[] = [
  'The solution is in the room',
  'Cool people do cool stuff',
  'Get shit done',
  'Do more with less',
  'Maximize effectiveness',
  'You are on mute',
  'Holistic approach',
  'Pain points',
  'Land the plane',
  'Best practice',
  'We always done it that way',
  'Customer obsession',
  'Help the team win',
  'Maybe ask Copilot',
  "That's why I like working with you most",
  'Great idea, I put it in the backlog',
  'Transparency',
  "Let's take a decision",
  'Conditional sign-off',
  'Half way gets you nowhere',
  'Well, with the dependencies given…',
  'In theory that sounds good',
  'Yes, and',
  'Yes, but',
  'Use synergies',
  'Culture transformation',
  'Change management',
  'Low hanging fruits',
  'Big picture',
  'Quick win',
  'Value proposition',
  'Accountability',
  'Digitilisation',
  'Scalability',
  'Resilience',
  'Sustainable growth',
  'KPI',
  'OKR',
  "It's the people that matter",
  'Is that goal realistic?',
  'Where is the journey going?',
  'A noticeable change is taking place',
  'Create value for customers',
  'Solution-oriented',
  'Move forward together',
  'On an equal footing',
  'Take ownership',
  'We drive the change',
  'Think outside the box',
  'High performing team',
  '"I" not "we"',
  'Fail forward',
  "Let's look at this together",
  'This is still being clarified',
  "We'll challenge this again",
  'We still need to align properly',
  'Not final yet',
  'This is a snapshot',
  'Quick wins',
  'Scoping',
  'Proceed iteratively',
  'Prioritise',
  'Roadmap',
  'Subject to change',
  'Needs review from legal perspective',
  'If possible',
  'Please interpret with caution',
  'Delivery is key',
  'Commitment',
];
